package cz.hombre.militaryReportsAssistant

class SpellingAlphabets {
    companion object {
        val NATO = mapOf(
                "a" to "Alpha",
                "b" to "Bravo",
                "c" to "Charlie",
                "d" to "Delta",
                "e" to "Echo",
                "f" to "Foxtrot",
                "g" to "Golf",
                "h" to "Hotel",
                "i" to "India",
                "j" to "Juliet",
                "k" to "Kilo",
                "l" to "Lima",
                "m" to "Mike",
                "n" to "November",
                "o" to "Oscar",
                "p" to "Papa",
                "q" to "Quebec",
                "r" to "Romeo",
                "s" to "Sierra",
                "t" to "Tango",
                "u" to "Uniform",
                "v" to "Victor",
                "w" to "Whiskey",
                "x" to "X-ray",
                "y" to "Yankee",
                "z" to "Zulu"
        )

        val CZECH = mapOf(
                "a" to "Adam",
                "á" to "Adam",
                "b" to "Božena",
                "c" to "Cyril",
                "č" to "Čeněk",
                "d" to "David",
                "ď" to "Ďáblice",
                "e" to "Emil",
                "é" to "Emil",
                "f" to "František",
                "g" to "Gustav",
                "h" to "Helena",
                "ch" to "Chrudim",
                "i" to "Ivan",
                "í" to "Ivan",
                "j" to "Josef",
                "k" to "Karel",
                "l" to "Ludvík",
                "m" to "Marie",
                "n" to "Norbert",
                "ň" to "Nina",
                "o" to "Otakar",
                "ó" to "Otakar",
                "p" to "Petr",
                "q" to "Quido",
                "r" to "Rudolf",
                "ř" to "Řehoř",
                "s" to "Svatopluk",
                "š" to "Štěpán",
                "t" to "Tomáš",
                "ť" to "Těšnov",
                "u" to "Urban",
                "ú" to "Urban",
                "ů" to "Urban",
                "v" to "Václav",
                "w" to "Dvojité V",
                "x" to "Xaver",
                "y" to "Ypsilon",
                "ý" to "Ypsilon",
                "z" to "Zuzana",
                "ž" to "Žofie"
        )
    }
}